# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - image/*

pool:
  name: linux 

steps:

- task: Bash@3
  displayName: "tests"
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      pwd
      
      ls -al image/ansible

- task: UsePythonVersion@0
  displayName: "Install Python"
  inputs:
    versionSpec: '3.7.3'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  displayName: "Install Ansible"
  inputs:
    targetType: 'inline'
    script: |
      python3 -m pip install --user ansible

- task: PackerTool@0
  displayName: "Packer Load"
  inputs:
    version: 

- task: Packer@1
  displayName: "Packer Init"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'init'

- task: Packer@1
  displayName: "Packer Build"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'build'
    variables: |
      CONFIG=configs/custom-job-delegate.hd.json
      EMAIL=ejensen99999@comcast.net
      NAME=custom-job-delegate
      IMAGE_REGISTRY_PATH=ejensen99999