# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - image/*

pool:
  name: linux 
  #vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  displayName: 'Copy Packer files to artifacts'
  inputs:
    SourceFolder: image
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      pwd
      
      ls -al

- task: PackerTool@0
  inputs:
    version: 

- task: Packer@1
  inputs:
    connectedServiceType: 'none'
    templatePath: '$(Build.ArtifactStagingDirectory)/image/linux/docker.pkr.hcl'
    command: 'init'
