# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - image/*

variables:
  - group: dockerHub
  - name: 'tag'
    value: 'latest'
  - name: 'repo'
    value: 'ejensen99999'
  - name: 'container'
    value: 'custom-job-delegate'
  - name: 'temp'
    value: 'ubuntu_base_image'

pool:
  name: linux 

steps:

- task: PackerTool@0
  displayName: "Packer Load"
  inputs:
    version: 

- task: Packer@1
  displayName: "Packer Init"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'init'

- task: Packer@1
  displayName: "Packer Build"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'build'
    variables: |
      SOURCE_DIR=$(Build.Repository.LocalPath)
      CONFIG=configs/$(container).hd.json
      EMAIL=ejensen99999@comcast.net
      NAME=$(container)
      IMAGE_REGISTRY_PATH=ejensen99999
      LOGIN_USER=$(LOGIN_USER)
      LOGIN_PASS=$(LOGIN_PASS)
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker rmi -f $(docker images -q $(repo)/$(container))
