# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - image/*

pool:
  name: linux 

steps:

- task: Bash@3
  displayName: "Set Location"
  name: setLocation
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      location=$(pwd)
      echo "##vso[task.setvariable variable=pwd; isoutput=true;]$location"



- task: PackerTool@0
  displayName: "Packer Load"
  inputs:
    version: 

- task: Packer@1
  displayName: "Packer Init"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'init'

- task: Packer@1
  displayName: "Packer Build"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'build'
    variables: |
      SOURCE_DIR=$(setLocation.pwd)
      CONFIG=configs/custom-job-delegate.hd.json
      EMAIL=ejensen99999@comcast.net
      NAME=custom-job-delegate
      IMAGE_REGISTRY_PATH=ejensen99999