# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - image/*

variables:
  group: dockerHub
  tag: 'ubuntu20.04'
  repo: 'ejensen99999/delegate-base'

pool:
  name: linux 

steps:

- task: Docker@2
  displayName: Build an image
  name: dockerBuild
  inputs:
    containerRegistry: 'dockerhub'
    repository: $(repo)
    command: 'buildAndPush'
    Dockerfile: '$(Build.Repository.LocalPath)/delegates/Dockerfile-Ubuntu'
    tags: |
      $(tag)

- task: PackerTool@0
  displayName: "Packer Load"
  inputs:
    version: 

- task: Packer@1
  displayName: "Packer Init"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'init'

- task: Packer@1
  displayName: "Packer Build"
  inputs:
    connectedServiceType: 'none'
    templatePath: 'image/linux/docker.pkr.hcl'
    command: 'build'
    variables: |
      SOURCE_IMAGE="$(repo):$(tag)"
      SOURCE_DIR=$(Build.Repository.LocalPath)
      CONFIG=configs/custom-job-delegate.hd.json
      EMAIL=ejensen99999@comcast.net
      NAME=custom-job-delegate
      IMAGE_REGISTRY_PATH=ejensen99999
      LOGIN_USER=$(LOGIN_USER)
      LOGIN_PASS=$(LOGIN_PASS)
