# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
- repo: self

variables:
  tag: 'latest'
  repo: 'ejensen99999/minimal_ubuntu_base'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: linux 

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        containerRegistry: 'dockerhub'
        repository: $(repo)
        Dockerfile: '$(Build.SourcesDirectory)/delegates/Dockerfile_Ubuntu'
        arguments: '--build-arg TARGETARCH=amd64 --build-arg DELEGATEVERSION=80505'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: 'push'
        containerRegistry: 'dockerhub'
        repository: $(repo)
        tags: |
          $(tag)
    

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker rmi -f $(docker images -q $(repo))
          
