# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
- repo: self

variables:
  tag: 'latest'
  repo: 'ejensen99999/minimal_ubuntu_base'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: linux 

    steps:
    - task: Docker@2
      displayName: Build an image
      name: dockerBuild
      inputs:
        repository: $(repo)
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/delegates/Dockerfile-Ubuntu'
        arguments: '--build-arg TARGETARCH=amd64 --build-arg DELEGATEVERSION=80505'
        tags: |
          $(tag)
    
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: '$(repo):$(tag)'
        command: 'push'

    # - task: Bash@3
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       docker rmi -f $(docker images -q $(repo))
          
