# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
- repo: self

variables:
  tag: 'latest'
  repo: 'ejensen99999/minimal_ubuntu_base'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: linux 

    steps:
    - task: Docker@2
      displayName: Build an image
      name: dockerBuild
      inputs:
        containerRegistry: 'dockerhub'
        repository: $(repo)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/delegates/Dockerfile-Ubuntu'
        tags: |
          $(tag)
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker rmi -f $(docker images -q $(repo))
          
