# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: linux 
      #vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      name: dockerBuild
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'ejensen99999/delegate-base'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/base_delegate/Dockerfile'
        tags: |
          $(tag)
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          readarray -t lines < <(echo "$(dockerBuild.DockerOutput)")
          file=${lines[0]}
          echo "-----"
          echo $file
          echo "-----"
          content=$(<file)
          echo "-----"
          echo $content
          echo "-----"
          
    