# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: linux 

steps:
- task: Bash@3
  displayName: "locations"
  inputs:
    targetType: 'inline'
    script: |
      location=$(pwd)
      echo $location
      echo $(Agent.BuildDirectory)
      echo $(Agent.HomeDirectory)
      echo $(Agent.WorkFolder)
      echo $(Build.ArtifactStagingDirectory)
      echo $(Build.Repository.LocalPath)

