---
# tasks file for harness
- name: Load configuration values
  ansible.builtin.include_tasks:  parse-config.yml

- name: Load Linux Configuration Values
  ansible.builtin.include_tasks:  linux.yml
  when: platform == 'linux'

- name: Load Windows Configuration Values
  ansible.builtin.include_tasks:  windows.yml
  when: platform == 'windows'
