---
- name: Load Linux Variables
  ansible.builtin.include_vars: linux.json

# - name: Create Kubernetes template
#   local_action:
#     module: ansible.builtin.template
#     src: ../agent/runner_deploy.yml.j2
#     dest: ../agent/{{ kube_name }}.yml
#   run_once: True

- name: Install Docker
  ansible.builtin.script:
    cmd: "docker.sh"
  environment:
    TARGETPLATFORM: "{{ targetPlatform }}"
    DOCKER_CHANNEL: "{{ dockerChannel }}"
    DOCKER_VERSION: "{{ dockerVersion }}"
    DOCKER_COMPOSE_VERSION: "{{ dockerComposeVersion }}"

- name: Install Docker shims
  ansible.builtin.script:
    cmd: "docker-shim.sh"
  environment:
    TARGETPLATFORM: "{{ targetPlatform }}"
    DOCKER_CHANNEL: "{{ dockerChannel }}"
    DOCKER_VERSION: "{{ dockerVersion }}"
    DOCKER_COMPOSE_VERSION: "{{ dockerComposeVersion }}"

# - name: Install Tool Cache
#   ansible.builtin.script:
#     cmd:  cache.sh

- name: Install Environment
  ansible.builtin.script:
    cmd: "{{ item }}"
  loop:
    - docker-config.sh