FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y \
        software-properties-common \
    && add-apt-repository --yes --update ppa:ansible/ansible \
    && apt install -y \
        ansible \
        ca-certificates \
        curl \
        gcc \
        krb5-user \
        libkrb5-dev \
        python3-pip \
        tree \
        wget \
    && pip3 install --upgrade pip \
    && pip3 install pywinrm[kerberos] \
    && pip3 install pywinrm \
    && pip3 install requests-credssp \
    && pip3 install -U requests-ntlm \
    && apt autoremove -y \
    && curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN ansible-galaxy collection list \
    && ansible-galaxy collection install azure.azcollection --force \
    && pip3 install -r /usr/lib/python3/dist-packages/ansible_collections/azure/azcollection/requirements-azure.txt 
    
WORKDIR /harness
CMD ["/bin/bash"]


