FROM alpine:3.18.4

RUN apk add ansible \
    && apk add --no-cache bash \
        openssh \
        curl \
        py3-pip \
    && curl -sL https://aka.ms/InstallAzureCLIDeb | bash 

WORKDIR /ansible
CMD ["/bin/sh"]


