# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

FROM ubuntu:20.04

LABEL name="harness/delegate" \
      vendor="Harness" \
      maintainer="Harness"

RUN apt update  \
  && apt install -y \
    procps \
    hostname \
    lsof \
    findutils \
    tar \
    gzip \
    git \
    locales \
    curl \
  && useradd -u 1001 -g 0 harness \
  && apt clean all \
  && locale-gen en_US.UTF-8 \
  && mkdir -p /opt/harness-delegate/

COPY support /opt/harness-delegate/

WORKDIR /opt/harness-delegate

COPY --from=adoptopenjdk/openjdk11:jre-11.0.19_7-ubuntu /opt/java/openjdk/ /opt/java/openjdk/

ENV LANG=en_US.UTF-8
ENV HOME=/opt/harness-delegate
ENV CLIENT_TOOLS_DOWNLOAD_DISABLED=true
ENV INSTALL_CLIENT_TOOLS_IN_BACKGROUND=true
ENV JAVA_HOME=/opt/java/openjdk/
ENV PATH="$JAVA_HOME/bin:${PATH}"

ARG TARGETARCH
ARG BASEURL=https://app.harness.io/public/shared/delegates
ARG DELEGATEVERSION

RUN chmod -R 775 /opt/harness-delegate \
  && chgrp -R 0 /opt/harness-delegate  \
  && chown -R 1001 /opt/harness-delegate \
  && chmod -R 777 /tmp

RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar

# USER 1001

CMD [ "./start.sh" ]